/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class dev_felnull_fnjl_jni_windows_WindowsNative */

#ifndef _Included_dev_felnull_fnjl_jni_windows_WindowsNative
#define _Included_dev_felnull_fnjl_jni_windows_WindowsNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_felnull_fnjl_jni_windows_WindowsNative
 * Method:    getSpecialFolderPath
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_dev_felnull_fnjl_jni_windows_WindowsNative_getSpecialFolderPath
  (JNIEnv *, jclass, jint);

/*
 * Class:     dev_felnull_fnjl_jni_windows_WindowsNative
 * Method:    getSystemFontFaceName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_dev_felnull_fnjl_jni_windows_WindowsNative_getSystemFontFaceName
  (JNIEnv *, jclass, jint);

/*
 * Class:     dev_felnull_fnjl_jni_windows_WindowsNative
 * Method:    getOpenFileName
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;II)[B
 */
JNIEXPORT jbyteArray JNICALL Java_dev_felnull_fnjl_jni_windows_WindowsNative_getOpenFileName
  (JNIEnv *, jclass, jlong, jstring, jstring, jstring, jstring, jstring, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
