name: cmake-build
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: build
        run: |
          cd C++/helloworld/
          mkdir build/
          cd build/
          cmake ..
          make