name: cmake-build
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          wget "https://cdn.discordapp.com/attachments/358878159615164416/925776793179418674/jni_md.h"
          wget "https://cdn.discordapp.com/attachments/358878159615164416/925776793389113374/jni.h"
          mkdir build/
          dir
          cmake -S . -B build/ -G"MinGW Makefiles" ..
          cmake --build build/
          ..