name: cmake-build
on:
  push:
    tags:
      - 't*'
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          curl "https://cdn.discordapp.com/attachments/358878159615164416/925776793179418674/jni_md.h" -O
          curl "https://cdn.discordapp.com/attachments/358878159615164416/925776793389113374/jni.h" -O
          mkdir build/
          cmake -S . -B build/ -G"Visual Studio 16 2019" ..
          cmake --build build/
          cd build/x64/Debug
          dir
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: FNJLWindowsNative-Release
          path: build/x64/Debug/FNJLNative.dll